abstract: Database operations for the MySpam application
author: Mark Lawrence <nomad@null.net>
build_requires: 
  Test::More: 0.42
distribution_type: module
generated_by: Module::Install version 0.64
license: GPL
name: MySpam
no_index: 
  directory: 
    - inc
    - t
recommends: 
  DBD::SQLite: 0
requires: 
  Compress::Bzip2: 0
  Config::File: 0
  Email::Simple: 0
  File::Slurp: 0
  LockFile::Simple: 0
  MIME::Base64: 0
  MIME::Lite: 0
  Mail::RFC822::Address: 0
  SQL::DB: 0.06
  Time::HiRes: 0
  XML::API::XHTML: 0.14
  perl: 5.0006
version: 0.05
